NewBaltimoreCity_SE_MapScripts::
	.byte 0


# 9 "data/maps/NewBaltimoreCity_SE/scripts.pory"

# 10 "data/maps/NewBaltimoreCity_SE/scripts.pory"

# 11 "data/maps/NewBaltimoreCity_SE/scripts.pory"
NewBaltimoreCity_SE_Trainspotting_HouseSign::
# 12 "data/maps/NewBaltimoreCity_SE/scripts.pory"
	msgbox Trainspotting_HouseSign, MSGBOX_SIGN
# 13 "data/maps/NewBaltimoreCity_SE/scripts.pory"
	end

Trainspotting_HouseSign::
# 5 "data/maps/NewBaltimoreCity_SE/scripts.pory"
	.string "RENTON'S HOUSE$"
