NewBaltimoreCity_Home_MapScripts::
	.byte 0


trainer_1::
# 4 "data/maps/NewBaltimoreCity_Home/scripts.pory"
	lockall
# 5 "data/maps/NewBaltimoreCity_Home/scripts.pory"
	msgbox trainer_1_Text_0
# 6 "data/maps/NewBaltimoreCity_Home/scripts.pory"
	releaseall
	return


trainer_2::
# 10 "data/maps/NewBaltimoreCity_Home/scripts.pory"
	lockall
# 11 "data/maps/NewBaltimoreCity_Home/scripts.pory"
	msgbox trainer_2_Text_0
# 12 "data/maps/NewBaltimoreCity_Home/scripts.pory"
	releaseall
	return


trainer_3::
# 16 "data/maps/NewBaltimoreCity_Home/scripts.pory"
	lockall
# 17 "data/maps/NewBaltimoreCity_Home/scripts.pory"
	msgbox trainer_3_Text_0
# 18 "data/maps/NewBaltimoreCity_Home/scripts.pory"
	releaseall
	return


trainer_1_Text_0:
# 5 "data/maps/NewBaltimoreCity_Home/scripts.pory"
	.string "I'm number one.$"

trainer_2_Text_0:
# 11 "data/maps/NewBaltimoreCity_Home/scripts.pory"
	.string "I'm number two.$"

trainer_3_Text_0:
# 17 "data/maps/NewBaltimoreCity_Home/scripts.pory"
	.string "I'm number three.$"
